// src/pages/shop/shop.data.js
import topImage from '../../components/assets/top.png'
import youngImage from '../../components/assets/young.png'

const SHOP_DATA = [
  {
    id: 1,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: topImage,
    price: 29.99,
    available: true,
    rating: 4.5,
    specific: 'dog',
    age: 'well',
    categories: 'dry food',
    filter:
    {age: 'well',
    breedSize: 'Large',
    brand: 'Brit care',
    material: 'without information',
    packageWeight: '1 kg',
    prescription: 'without information',},
        describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 2,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: youngImage,
    price: 19.99,
    available: true,
    rating: 3.8,
    specific: 'dog',
    age: 'young',
    categories: 'wet food',
    filter: {
    age: 'young',
    breedSize: 'Small',
    brand: 'whiskas',
    material: 'without information',
    packagWeight: '2 kg',
    prescription: 'without information',},
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 3,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: topImage,
    price: 20.99,
    available: true,
    rating: 4.6,
    specific: 'dog',
    age: 'well',
    categories: 'vet-prescribet food',
    filter: {
    age: 'well',
breedSize: 'X-Small',
brand: 'Royal Canin',
material: 'without information',
packageWeight: 'more than 2 kg kg',
prescription: 'without information',},
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 4,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: youngImage,
    price: 20.99,
    available: true,
    rating: 3.8,
    specific: 'cat',
    age: 'young',
    categories: 'vitamins & supplements',
    breedSize: 'Large',
    brand: 'Brit care',
    material: 'without information',
    packageWeight: '1 kg',
    prescription: 'without information',
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 5,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: youngImage,
    price: 20.99,
    available: true,
    rating: 3.8,
    specific: 'dog',
    age: 'young',
    categories: 'wet food',
breedSize: 'Medium',
brand: 'club 4 paws',
material: 'without information',
packageWeight: '2 kg',
prescription: 'without information',
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 6,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: topImage,
    price: 20.99,
    available: true,
    rating: 4.8,
    specific: 'cat',
    age: 'well',
    categories: 'treats',
    breedSize: 'Large',
    brand: 'Royal Canin',
    material: 'without information',
    packageWeight: '1 kg',
    prescription: 'without information',
    
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 7,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: topImage,
    price: 20.99,
    available: true,
    rating: 4.2,
    specific: 'dog',
    age: 'well',
    categories: 'dry food',
    breedSize: 'X-Large',
    brand: 'club 4 paws',
    material: 'without information',
    packageWeight: '1 kg',
    prescription: 'without information',
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 8,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: youngImage,
    price: 20.99,
    available: true,
    rating: 3.8,
    specific: 'cat',
    age: 'young',
    categories: 'dry food',
    breedSize: 'X-Large',
    brand: 'club 4 paws',
    material: 'without information',
    packageWeight: '1 kg',
    prescription: 'without information',
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 9,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: youngImage,
    price: 20.99,
    available: true,
    rating: 3.8,
    specific: 'dog',
    age: 'young',
    categories: 'treats',
breedSize: 'Large',
brand: 'Royal Canin',
material: 'without information',
packageWeight: '1 kg',
prescription: 'without information',
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },

  {
    id: 10,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: topImage,
    price: 20.99,
    available: true,
    rating: 4.1,
    specific: 'cat',
    age: 'well',
    categories: 'wet food',
    breedSize: 'Medium',
    brand: 'club 4 paws',
    material: 'without information',
    packageWeight: '2 kg',
    prescription: 'without information',
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 11,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: youngImage,
    price: 20.99,
    available: true,
    rating: 3.8,
    specific: 'cat',
    age: 'young',
    categories: 'vitamins & supplements',
    breedSize: 'Large',
    brand: 'Brit care',
    material: 'without information',
    packageWeight: '1 kg',
    prescription: 'without information',
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 12,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: youngImage,
    price: 29.99,
    available: true,
    rating: 4.5,
    specific: 'dog',
    age: 'young',
    categories: 'vet-prescribet food',
    breedSize: 'X-Small',
    brand: 'Royal Canin',
    material: 'without information',
    packageWeight: 'more than 2 kg kg',
    prescription: 'without information',
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 13,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: topImage,
    price: 19.99,
    available: true,
    rating: 4.05,
    specific: 'dog',
    age: 'well',
    categories: 'wet food',
    breedSize: 'Small',
    brand: 'whiskas',
    material: 'without information',
    packagWeight: '2 kg',
    prescription: 'without information',
    
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 14,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: topImage,
    price: 20.99,
    available: true,
    rating: 4.1,
    specific: 'dog',
    age: 'well',
    categories: 'dry food',
breedSize: 'Large',
brand: 'Brit care',
material: 'without information',
packageWeight: '1 kg',
prescription: 'without information',
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 15,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: youngImage,
    price: 20.99,
    available: true,
    rating: 3.8,
    specific: 'cat',
    age: 'young',
    categories: 'dry food',
breedSize: 'Large',
brand: 'Brit care',
material: 'without information',
packageWeight: '1 kg',
prescription: 'without information',
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 16,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: youngImage,
    price: 20.99,
    available: true,
    rating: 3.8,
    specific: 'dog',
    age: 'young',
    categories: 'wet food',
    breedSize: 'Small',
brand: 'whiskas',
material: 'without information',
packagWeight: '2 kg',
prescription: 'without information',
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 17,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: topImage,
    price: 20.99,
    available: true,
    rating: 4.6,
    specific: 'cat',
    age: 'well',
    categories: 'vet-prescribet food',
breedSize: 'X-Small',
brand: 'Royal Canin',
material: 'without information',
packageWeight: 'more than 2 kg kg',
prescription: 'without information',
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 18,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: youngImage,
    price: 20.99,
    available: true,
    rating: 3.8,
    specific: 'dog',
    age: 'young',
    categories: 'vitamins & supplements',
    breedSize: 'Large',
    brand: 'Brit care',
    material: 'without information',
    packageWeight: '1 kg',
    prescription: 'without information',
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 19,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: topImage,
    price: 20.99,
    available: true,
    rating: 4.2,
    specific: 'cat',
    age: 'well',
 categories: 'wet food',
breedSize: 'Medium',
brand: 'club 4 paws',
material: 'without information',
packageWeight: '2 kg',
prescription: 'without information',
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 20,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: youngImage,
    price: 20.99,
    available: true,
    rating: 3.8,
    specific: 'dog',
    age: 'young',
    categories: 'treats',
    breedSize: 'Large',
    brand: 'Royal Canin',
    material: 'without information',
    packageWeight: '1 kg',
    prescription: 'without information',
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 21,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: youngImage,
    price: 20.99,
    available: true,
    rating: 3.8,
    specific: 'cat',
    age: 'young',
    categories: 'dry food',
    breedSize: 'X-Large',
    brand: 'club 4 paws',
    material: 'without information',
    packageWeight: '1 kg',
    prescription: 'without information',
    
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 22,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: topImage,
    price: 20.99,
    available: true,
    rating: 4.7,
    specific: 'cat',
    age: 'well',
    categories: 'dry food',
    breedSize: 'X-Large',
    brand: 'club 4 paws',
    material: 'without information',
    packageWeight: '1 kg',
    prescription: 'without information',
    
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 23,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: youngImage,
    price: 20.99,
    available: true,
    rating: 3.8,
    specific: 'dog',
    age: 'young',
    categories: 'vitamins & supplements',
    breedSize: 'Large',
    brand: 'Brit care',
    material: 'without information',
    packageWeight: '1 kg',
    prescription: 'without information',
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  {
    id: 24,
    name: 'Whiskas Tasty Mix Seafood Cocktail',
    imageUrl: topImage,
    price: 19.99,
    available: true,
    rating: 4.5,
    specific: 'dog',
    age: 'well',
    categories: 'wet food',
    breedSize: 'Small',
    brand: 'whiskas',
    material: 'without information',
    packagWeight: '2 kg',
    prescription: 'without information',
    describe:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  ',
  },
  // Додайте інші дані для товарів тут
]

export default SHOP_DATA
